=== ChloeSAPage/Coding-Challenges/XML/files/target.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (entry)+>
<!ELEMENT entry (firstname, lastname, email)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== ChloeSAPage/Coding-Challenges/XML/target.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "target.dtd">
<list>
	<entry>
		<firstname>Joe</firstname>
		<lastname>Bloggs</lastname>
		<email>j.bloggs@sample.co.uk</email>
	</entry>
	<entry>
		<firstname>Winston</firstname>
		<lastname>Smith</lastname>
		<email>w.smith@airstripOne.gov</email>
	</entry>
	<entry>
		<firstname>John</firstname>
		<lastname>Smith</lastname>
		<email>john.smith@somewhere.com</email>
	</entry>
	<entry>
		<firstname>Thorin</firstname>
		<lastname>Oakenshield</lastname>
		<email>chief@dwarvesreunited.com</email>
	</entry>
	<entry>
		<firstname>Bugs</firstname>
		<lastname>Bunny</lastname>
		<email>bugs.bunny@looney.com</email>
	</entry>
	<entry>
		<firstname>Anna</firstname>
		<lastname>Andrews</lastname>
		<email>a.andrews@andrews.co.uk</email>
	</entry>
	<entry>
		<firstname>Mickey</firstname>
		<lastname>Mouse</lastname>
		<email>mickey@disney.com</email>
	</entry>
	<entry>
		<firstname>Ruth</firstname>
		<lastname>Rendell</lastname>
		<email>ruthrendell@authors.com</email>
	</entry>
	<entry>
		<firstname>Donald</firstname>
		<lastname>Duck</lastname>
		<email>duck@disney.com</email>
	</entry>
	<entry>
		<firstname/>
		<lastname/>
		<email>a.nonymous@mailinator.com</email>
	</entry>
	<entry>
		<firstname>Han</firstname>
		<lastname>Solo</lastname>
		<email>pilot@milleniumfalcon.co.sw</email>
	</entry>
	<entry>
		<firstname>Bilbo</firstname>
		<lastname>Baggins</lastname>
		<email>bilbo.baggins@theshire.co.nz</email>
	</entry>
	<entry>
		<firstname>Arthur</firstname>
		<lastname>Pendragon</lastname>
		<email>king.arthur@camelot.co.uk</email>
	</entry>
	<entry>
		<firstname>Sherlock</firstname>
		<lastname>Holmes</lastname>
		<email>detective@bakerstreet.gov.uk</email>
	</entry>
	<entry>
		<firstname>Robin</firstname>
		<lastname>Hood</lastname>
		<email>robin@loxley.co.uk</email>
	</entry>
	<entry>
		<firstname>Luke</firstname>
		<lastname>Skywalker</lastname>
		<email>son.of.darth@tatooine.com</email>
	</entry>
	<entry>
		<firstname>William</firstname>
		<lastname>Shakespeare</lastname>
		<email>bill@stratford.co.uk</email>
	</entry>
	<entry>
		<firstname>Moby</firstname>
		<lastname>Dick</lastname>
		<email>whale@melville.com</email>
	</entry>
	<entry>
		<firstname>Endeavour</firstname>
		<lastname>Morse</lastname>
		<email>morse@thamesvalleypolice.co.uk</email>
	</entry>
	<entry>
		<firstname>Oliver</firstname>
		<lastname>Twist</lastname>
		<email>oliver@workhouse.org</email>
	</entry>
	<entry>
		<firstname/>
		<lastname/>
		<email>anon.ymous@mailinator.com</email>
	</entry>
	<entry>
		<firstname>Harry</firstname>
		<lastname>Potter</lastname>
		<email>harry.potter@hogwarts.ac.uk</email>
	</entry>
	<entry>
		<firstname/>
		<lastname/>
		<email>no.details@shy.com</email>
	</entry>
</list>
